<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Dimensionality-Reduction" data-toc-modified-id="Dimensionality-Reduction-1">Dimensionality Reduction</a></span></li><li><span><a href="#Latent-Semantic-Analysis" data-toc-modified-id="Latent-Semantic-Analysis-2">Latent Semantic Analysis</a></span></li><li><span><a href="#numpy를-이용한-cosine-similarity-계산" data-toc-modified-id="numpy를-이용한-cosine-similarity-계산-3">numpy를 이용한 cosine similarity 계산</a></span></li><li><span><a href="#SVD(Singular-Value-Decomposition)" data-toc-modified-id="SVD(Singular-Value-Decomposition)-4">SVD(Singular Value Decomposition)</a></span></li><li><span><a href="#exam1" data-toc-modified-id="exam1-5">exam1</a></span></li><li><span><a href="#Exam2" data-toc-modified-id="Exam2-6">Exam2</a></span></li><li><span><a href="#뉴스-데이터에-SVD-적용한-Clustering" data-toc-modified-id="뉴스-데이터에-SVD-적용한-Clustering-7">뉴스 데이터에 SVD 적용한 Clustering</a></span></li></ul></div>

### Dimensionality Reduction

- https://opentutorials.org/module/3653/22994

![Dimensionality_Reduction.png](./images/Dimensionality_Reduction.png)

차원 축소 (Dimensionality Reduction)는 어떤 목적에 따라서 데이터의 양을 줄이는 방법입니다.

차원 축소로 데이터의 양을 일부러 줄여서 사용하는 이유는

첫째로, 데이터의 양이 줄어든다면 <br>
기본적으로 시간 복잡도 (time complexity, 계산하는 시간)와 공간 복잡도 (space complexity, 저장하는 변수의 양)가 줄어듭니다.

둘째로, 아주 많은 차원의 데이터로 학습시킨 머신러닝 모델은 내부의 파라미터도 매우 복잡하게 형성되기 때문에 (=overfit 되기가 쉽기 때문에), <br>
적은 양의 데이터에 대해서 이리 휘청 저리 휘청 불안정한 결과를 내놓게 됩니다. <br>
입력 데이터의 차원을 줄여서 학습을 시키면 모델이 비교적 간단해지고, 그러면 적은 데이터 셋에 대해 안정적(robust)인 결과를 내놓게 됩니다.
 
셋째로, 간단한 모델일수록 사람이 그 내부 구조를 이해하기에 편하고 (interpretable), <br>
모델이 내놓은 결과를 2차원이나 3차원의 그림으로 축소해 드러내어서, 사람이 결과를 알아보기에 편합니다. 

차원축소 방법은, 원본 데이터를 훼손하는 것이므로 있던 정보를 일부 없애버리게 됩니다.<br>
어떤 목적 아래에서 어떤 정보를 얼만큼 없애면 좋을까에 대한 고민과 그 결과가 차원축소 방법입니다.

그림은 총 세 파트로 나뉘어 있습니다.<br>
우상단의 분홍색 배경에는 데이터를 표현해 놓았습니다.

차원축소를 하는 방식에는 크게 두 가지가 있는데요,<br>
상단의 짙은 회색 배경에는 feature selection 방법을 그려놓았습니다.<br>
하단의 옅은 회색 배경에는 feature extraction 방법을 그려놓았습니다.

### Latent Semantic Analysis

- https://ratsgo.github.io/from%20frequency%20to%20semantics/2017/04/06/pcasvdlsa/

잠재의미분석이란 단어-문서행렬(Word-Document Matrix), 단어-문맥행렬(window based co-occurrence matrix) 등 입력 데이터에 특이값 분해를 수행해 데이터의 차원수를 줄여 계산 효율성을 키우는 한편 행간에 숨어있는(latent) 의미를 이끌어내기 위한 방법론입니다.

잠재의미분석을 수행하는 절차는 이렇습니다. 

n개의 문서를 m개의 단어로 표현된 입력데이터 행렬 A가 주어졌다고 칩시다. 

A의 0보다 큰 고유값의 개수를 r이라고 할 때, r보다 작은 k를 연구자가 임의로 설정하고 $\Sigma_k$를 만듭니다. <br>
이후 $U$와 $V$행렬에서 여기에 대응하는 부분만 남겨 $U_k$와 $V_k$를 만들어줍니다. <br>
이렇게 되면 $A$와 비슷한 $A_k$ 행렬을 구축할 수 있습니다.

$A_k = U_k \Sigma_k V_t^T$

![LSA](./images/LSA.png)

위 식 양변에 $U_k$의 전치행렬을 곱해준 것을 $X_1$, $V_k$를 곱해준 것을 $X_2$라고 둡니다. <br>
그러면 $X_1$의 경우 n개의 문서는 원래 단어수 m보다 훨씬 작은 k개 변수로 표현된 결과가 됩니다. <br>
$X_2$는 m개의 단어가 원래 문서 수 n보다 작은 k개 변수로 표현한 결과입니다. 

이는 주성분 분석에서의 차원축소 효과와 비슷한 것으로 이해하면 좋을 것 같습니다.

$U^T_k A_k = U^T_k U_k \Sigma_k V^T_k = I \Sigma_k V^T_k = \Sigma_k V^T_k = X_1$

$A_k V_k = U_k \Sigma_k V^T_k V_k = U_k \Sigma_k I = U_k \Sigma_k = X_2$

### numpy를 이용한 cosine similarity 계산

In [1]:
import numpy as np

In [7]:
X = np.array([[1, 1, 0, 0, 0],
                    [0, 1, 0, 0, 0],
                    [0, 0, 1, 0, 0],
                    [0, 0, 0, 1, 0],
                    [0, 0, 0, 0, 1]])

In [28]:
X, X.shape, X.ndim
# Term-Document Matric
# Row: Terms
# Column: Documents

# Document-Term Matrix
# Row: Documrnts
# Column: Terms

(array([[1, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]]), (5, 5), 2)

In [22]:
X.T

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
_X = X.dot(X.T)
_X

array([[2, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
np.matmul(X, X.T)

array([[2, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
def cosine(x, y):
    return inner_product(x, y) / (len(x)*len(y))     # len(x), len(y) : norm

def inner_product(x, y):
    return x * y

In [34]:
np.linalg.norm(X[0])

1.4142135623730951

In [35]:
np.linalg.norm(X, axis=1)    # 행의 길이 : 문서의 길이

array([1.41421356, 1.        , 1.        , 1.        , 1.        ])

In [39]:
np.linalg.norm(X.T, axis=0)    # 열의 길이 : term의 길이

array([1.41421356, 1.        , 1.        , 1.        , 1.        ])

In [44]:
# cosine similarity
X.dot(X.T) / np.linalg.norm(X, axis=1).reshape(5, 1)  * np.linalg.norm(X.T, axis=0)

array([[2.        , 0.70710678, 0.        , 0.        , 0.        ],
       [1.41421356, 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

### SVD(Singular Value Decomposition)

특이값분해는 m x n 크기의 데이터 행렬 $A$를 아래와 같이 분해하는 걸 말합니다.

![SVD](./images/SVD.png)

- $SVD: C = UΣV^T$ (where C = term-document matrix)

![lsi](./images/LSI.png)

In [2]:
import pandas as pd

In [85]:
words = ["ship", "boat", "ocean", "wood", "tree"]
documents = ["d1", "d2", "d3", "d4", "d5", "d6"]

In [154]:
C = np.array([[1, 0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0, 0],
              [1, 1, 0, 0, 0, 0],
              [1, 0, 0, 1, 1, 0],
              [0, 0, 0, 1, 0, 1]    
])

In [93]:
pd.DataFrame(C, index=words, columns=documents)

       d1  d2  d3  d4  d5  d6
ship    1   0   1   0   0   0
boat    0   1   0   0   0   0
ocean   1   1   0   0   0   0
wood    1   0   0   1   1   0
tree    0   0   0   1   0   1

In [57]:
# C: M x N
# U: M x K
# sigma: K, K   => K = min(M, N)  => 5: (클러스터의 수 또는 잠재의미의 수)
# VT: K, N
U, sigma, VT = np.linalg.svd(C, full_matrices=False)

In [91]:
pd.DataFrame(U, index=words)

              0         1         2             3         4
ship   0.440347 -0.296174 -0.569498  5.773503e-01 -0.246402
boat   0.129346 -0.331451  0.587022  9.436896e-16 -0.727197
ocean  0.475530 -0.511115  0.367690  4.518514e-16  0.614358
wood   0.703020  0.350572 -0.154906 -5.773503e-01 -0.159788
tree   0.262673  0.646747  0.414592  5.773503e-01  0.086614

In [79]:
sigma   # Latent Semantic => U x sigma: Term의 중요도,     sigma x VT: Document의 중요도

array([2.16250096, 1.59438237, 1.27529025, 1.        , 0.39391525])

In [92]:
_sigma = np.diag(sigma)
pd.DataFrame(_sigma)

          0         1        2    3         4
0  2.162501  0.000000  0.00000  0.0  0.000000
1  0.000000  1.594382  0.00000  0.0  0.000000
2  0.000000  0.000000  1.27529  0.0  0.000000
3  0.000000  0.000000  0.00000  1.0  0.000000
4  0.000000  0.000000  0.00000  0.0  0.393915

In [94]:
pd.DataFrame(VT, columns=documents)

             d1            d2        d3            d4        d5        d6
0  7.486230e-01  2.797116e-01  0.203629  4.465631e-01  0.325096  0.121467
1 -2.864540e-01 -5.284591e-01 -0.185761  6.255207e-01  0.219880  0.405641
2 -2.797116e-01  7.486230e-01 -0.446563  2.036288e-01 -0.121467  0.325096
3 -4.162907e-16  1.066959e-15  0.577350  2.382035e-16 -0.577350  0.577350
4  5.284591e-01 -2.864540e-01 -0.625521 -1.857612e-01 -0.405641  0.219880

In [99]:
# C = UΣVT
pd.DataFrame(U.dot(_sigma).dot(VT), index=words, columns=documents)

,d1,d2,d3,d4,d5,d6
ship,1.000000e+00,2.866176e-16,1.000000e+00,-2.957499e-16,1.371194e-16,-3.707870e-16
boat,-5.863986e-17,1.000000e+00,-1.655668e-16,1.602963e-16,7.954781e-17,-4.819879e-17
ocean,1.000000e+00,1.000000e+00,-5.924052e-16,-5.787719e-17,1.733548e-17,-1.454892e-16
wood,1.000000e+00,6.760135e-17,-1.334818e-16,1.000000e+00,1.000000e+00,2.535997e-16
tree,-3.275686e-16,-5.436625e-16,-4.857263e-16,1.000000e+00,2.091058e-16,1.000000e+00

In [100]:
# C와 동일하지는 않지만, 거의 유사함
pd.DataFrame(np.round(U.dot(_sigma).dot(VT)), index=words, columns=documents)

        d1   d2   d3   d4   d5   d6
ship   1.0  0.0  1.0 -0.0  0.0 -0.0
boat  -0.0  1.0 -0.0  0.0  0.0 -0.0
ocean  1.0  1.0 -0.0 -0.0  0.0 -0.0
wood   1.0  0.0 -0.0  1.0  1.0  0.0
tree  -0.0 -0.0 -0.0  1.0  0.0  1.0

In [108]:
# U x sigma: latent semantic(sigma) 차원에서 Term의 중요도(reduced matrix)
pd.DataFrame(U.dot(_sigma), index=words)

              0         1         2             3         4
ship   0.952252 -0.472215 -0.726275  5.773503e-01 -0.097062
boat   0.279712 -0.528459  0.748623  9.436896e-16 -0.286454
ocean  1.028335 -0.814913  0.468911  4.518514e-16  0.242005
wood   1.520282  0.558946 -0.197550 -5.773503e-01 -0.062943
tree   0.568030  1.031162  0.528725  5.773503e-01  0.034119

In [109]:
# sigma x VT: latent semantic(sigma) 차원에서 Document의 중요도(reduced matrix)
pd.DataFrame(_sigma.dot(VT), index=words, columns=documents)

                 d1            d2        d3            d4        d5        d6
ship   1.618898e+00  6.048766e-01  0.440347  9.656932e-01  0.703020  0.262673
boat  -4.567172e-01 -8.425659e-01 -0.296174  9.973192e-01  0.350572  0.646747
ocean -3.567135e-01  9.547117e-01 -0.569498  2.596858e-01 -0.154906  0.414592
wood  -4.162907e-16  1.066959e-15  0.577350  2.382035e-16 -0.577350  0.577350
tree   2.081681e-01 -1.128386e-01 -0.246402 -7.317416e-02 -0.159788  0.086614

In [148]:
# Latent Sematic 차원에서의 Term의 cosine similarity
_U = U.dot(np.diag(sigma))
cos_sim_U = _U.dot(_U.T) / (np.linalg.norm(_U, axis=1).reshape(5,1) * np.linalg.norm(_U.T, axis=0))
pd.DataFrame(np.round(cos_sim_U*100), index=words, columns=words)

        ship   boat  ocean   wood   tree
ship   100.0   -0.0   50.0   41.0   -0.0
boat    -0.0  100.0   71.0   -0.0   -0.0
ocean   50.0   71.0  100.0   41.0   -0.0
wood    41.0   -0.0   41.0  100.0   41.0
tree    -0.0   -0.0   -0.0   41.0  100.0

In [149]:
# Latent Sematic 차원에서의 document의 cosine similarity
_V = np.diag(sigma).dot(VT)
cos_sim_V = _V.T.dot(_V) / (np.linalg.norm(_V.T, axis=1).reshape(6,1) * np.linalg.norm(_V, axis=0))
pd.DataFrame(np.round(cos_sim_V*100), index=documents, columns=documents)

       d1     d2     d3     d4     d5     d6
d1  100.0   41.0   58.0   41.0   58.0   -0.0
d2   41.0  100.0   -0.0   -0.0    0.0   -0.0
d3   58.0   -0.0  100.0   -0.0   -0.0   -0.0
d4   41.0   -0.0   -0.0  100.0   71.0   71.0
d5   58.0    0.0   -0.0   71.0  100.0    0.0
d6   -0.0   -0.0   -0.0   71.0    0.0  100.0

In [161]:
_U = U[:, :2].dot(_sigma[:2])    # 차원 축소
cos_sim_U = _U.dot(_U.T) / (np.linalg.norm(_U, axis=1).reshape(5,1) * np.linalg.norm(_U.T, axis=0))
pd.DataFrame(cos_sim_U, index=words, columns=words)

           ship      boat     ocean      wood      tree
ship   1.000000  0.811764  0.978079  0.687557  0.043137
boat   0.811764  1.000000  0.915575  0.134084 -0.548426
ocean  0.978079  0.915575  1.000000  0.521280 -0.165849
wood   0.687557  0.134084  0.521280  1.000000  0.755113
tree   0.043137 -0.548426 -0.165849  0.755113  1.000000

In [163]:
cluster = pd.DataFrame(cos_sim_U, index=words)
temp = cluster.sort_values(by=[1], ascending=False)
temp[temp[1] > 0][1].to_dict()

{'boat': 1.0,
 'ocean': 0.9155748759872768,
 'ship': 0.8117637410018149,
 'wood': 0.13408431998247014}

In [164]:
temp = cluster.sort_values(by=[0], ascending=False)
temp[temp[0] > 0][0].to_dict()

{'ship': 1.0000000000000002,
 'ocean': 0.9780790149520933,
 'boat': 0.8117637410018149,
 'wood': 0.6875573362073368,
 'tree': 0.043136502613820224}

### exam1

1. SVD => U, Sigma, Vt => (N, M), N개의 문서와 M개의 단어
2. U.Sigma : U[:, :K].Sigma[:K] => Latent Semantic 차원에서 어느 문서가 중요한지
3. Sigma.Vt : Sigma[:, :K].Vt[:K, :] => Lagent Semantic 차원에서 어느 단어가 중요한지
4. 2-> 각 문서가 어느 문서와 유사한지 (on Latent Semantic Dimensions)
5. 3-> 각 단어가 어느 단어와 유사한지 (on Latent Semantic Dimensions)

In [174]:
C = np.array([
    [1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 1, 1, 0, 0],
    [1, 0, 1, 0, 1, 1, 1]
])

In [178]:
doc = ["A", "B", "C", "D", "E", "F"]
term = ["cute", "kitty", "eat", "rice", "cake", "hamster", "bread"]

In [204]:
pd.DataFrame(C, index=doc, columns=term)

   cute  kitty  eat  rice  cake  hamster  bread
A     1      1    0     0     0        0      0
B     0      0    1     1     1        0      0
C     0      1    0     0     0        1      0
D     0      0    1     0     0        0      1
E     0      0    0     1     1        0      0
F     1      0    1     0     1        1      1

In [205]:
U, sigma, VT = np.linalg.svd(C, full_matrices=False)
U.shape, sigma.shape, VT.shape

((6, 6), (6,), (6, 7))

In [207]:
_sigma = np.diag(sigma)
pd.DataFrame(_sigma)

          0        1         2    3         4         5
0  2.822643  0.00000  0.000000  0.0  0.000000  0.000000
1  0.000000  1.89393  0.000000  0.0  0.000000  0.000000
2  0.000000  0.00000  1.562689  0.0  0.000000  0.000000
3  0.000000  0.00000  0.000000  1.0  0.000000  0.000000
4  0.000000  0.00000  0.000000  0.0  0.899362  0.000000
5  0.000000  0.00000  0.000000  0.0  0.000000  0.441438

In [224]:
_U = U[:, :2].dot(_sigma[:2])
_U

array([[ 0.4185015 , -0.91368177,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.34429039,  0.94566246,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.4185015 , -0.91368177,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.92201403, -0.07999361,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.79892052,  0.85384019,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 2.07882785, -0.53630501,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [225]:
pd.DataFrame(U[:, :2].dot(_sigma[:2]), index=doc)

          0         1    2    3    4    5
A  0.418502 -0.913682  0.0  0.0  0.0  0.0
B  1.344290  0.945662  0.0  0.0  0.0  0.0
C  0.418502 -0.913682  0.0  0.0  0.0  0.0
D  0.922014 -0.079994  0.0  0.0  0.0  0.0
E  0.798921  0.853840  0.0  0.0  0.0  0.0
F  2.078828 -0.536305  0.0  0.0  0.0  0.0

In [227]:
_V = _sigma[:, :2].dot(VT[:2, :])
_V

array([[ 0.88474861,  0.29653167,  1.53938435,  0.75929227,  1.49577504,
         0.88474861,  1.06313197],
       [-0.76559676, -0.96485267,  0.17390496,  0.95014204,  0.66697161,
        -0.76559676, -0.32540726],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [228]:
pd.DataFrame(_sigma[:, :2].dot(VT[:2, :]), columns=term)

       cute     kitty       eat      rice      cake   hamster     bread
0  0.884749  0.296532  1.539384  0.759292  1.495775  0.884749  1.063132
1 -0.765597 -0.964853  0.173905  0.950142  0.666972 -0.765597 -0.325407
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

In [229]:
# Latent Sematic 차원에서의 Document의 cosine similarity
cos_sim_U = _U.dot(_U.T) / (np.linalg.norm(_U, axis=1).reshape(6,1) * np.linalg.norm(_U.T, axis=0))
pd.DataFrame(np.round(cos_sim_U*100), index=doc, columns=doc)

       A      B      C      D      E      F
A  100.0  -18.0  100.0   49.0  -38.0   63.0
B  -18.0  100.0  -18.0   77.0   98.0   65.0
C  100.0  -18.0  100.0   49.0  -38.0   63.0
D   49.0   77.0   49.0  100.0   62.0   99.0
E  -38.0   98.0  -38.0   62.0  100.0   48.0
F   63.0   65.0   63.0   99.0   48.0  100.0

In [230]:
# Latent Sematic 차원에서의 Term의 cosine similarity
cos_sim_V = _V.T.dot(_V) / (np.linalg.norm(_V.T, axis=1).reshape(7,1) * np.linalg.norm(_V, axis=0))
pd.DataFrame(np.round(cos_sim_V*100), columns=term, index=term)

          cute  kitty    eat   rice   cake  hamster  bread
cute     100.0   85.0   68.0   -4.0   42.0    100.0   91.0
kitty     85.0  100.0   18.0  -56.0  -12.0     85.0   56.0
eat       68.0   18.0  100.0   71.0   95.0     68.0   92.0
rice      -4.0  -56.0   71.0  100.0   89.0     -4.0   37.0
cake      42.0  -12.0   95.0   89.0  100.0     42.0   75.0
hamster  100.0   85.0   68.0   -4.0   42.0    100.0   91.0
bread     91.0   56.0   92.0   37.0   75.0     91.0  100.0

In [238]:
cluster = pd.DataFrame(cos_sim_U, index=doc)
cluster

          0         1         2         3         4         5
A  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345
B -0.182501  1.000000 -0.182501  0.765105  0.978945  0.648239
C  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345
D  0.493458  0.765105  0.493458  1.000000  0.617561  0.986264
E -0.379352  0.978945 -0.379352  0.617561  1.000000  0.479164
F  0.630345  0.648239  0.630345  0.986264  0.479164  1.000000

In [239]:
temp = cluster.sort_values(by=[1], ascending=False)     # 0번째는 모든 문서에 다 포함되는 중요하지 않은 정보이므로, 1번째를 기준으로 정렬
temp

          0         1         2         3         4         5
B -0.182501  1.000000 -0.182501  0.765105  0.978945  0.648239
E -0.379352  0.978945 -0.379352  0.617561  1.000000  0.479164
D  0.493458  0.765105  0.493458  1.000000  0.617561  0.986264
F  0.630345  0.648239  0.630345  0.986264  0.479164  1.000000
C  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345
A  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345

In [240]:
temp[temp[1] > 0][1].to_dict()

{'B': 1.0000000000000002,
 'E': 0.9789454660748421,
 'D': 0.7651054648220396,
 'F': 0.6482386350719546}

In [241]:
temp = cluster.sort_values(by=[0], ascending=False)  # 0번째를 기준으로 정렬하는 경우 의미 있는 순위를 찾기 어려움
temp

          0         1         2         3         4         5
A  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345
C  1.000000 -0.182501  1.000000  0.493458 -0.379352  0.630345
F  0.630345  0.648239  0.630345  0.986264  0.479164  1.000000
D  0.493458  0.765105  0.493458  1.000000  0.617561  0.986264
B -0.182501  1.000000 -0.182501  0.765105  0.978945  0.648239
E -0.379352  0.978945 -0.379352  0.617561  1.000000  0.479164

In [242]:
temp[temp[0] > 0][0].to_dict()

{'A': 0.9999999999999998,
 'C': 0.9999999999999998,
 'F': 0.6303451754109326,
 'D': 0.49345847594937386}

In [244]:
cluster = pd.DataFrame(cos_sim_V, columns=term)
cluster

       cute     kitty       eat      rice      cake   hamster     bread
0  1.000000  0.847627  0.677955 -0.039102  0.424155  1.000000  0.914593
1  0.847627  1.000000  0.184613 -0.563331 -0.120974  0.847627  0.560674
2  0.677955  0.184613  1.000000  0.708032  0.953260  0.677955  0.917311
3 -0.039102 -0.563331  0.708032  1.000000  0.888312 -0.039102  0.368305
4  0.424155 -0.120974  0.953260  0.888312  1.000000  0.424155  0.754128
5  1.000000  0.847627  0.677955 -0.039102  0.424155  1.000000  0.914593
6  0.914593  0.560674  0.917311  0.368305  0.754128  0.914593  1.000000

In [249]:
temp = cluster.sort_values(by=[1], axis=1, ascending=False)
temp.T

                0         1         2         3         4         5         6
kitty    0.847627  1.000000  0.184613 -0.563331 -0.120974  0.847627  0.560674
hamster  1.000000  0.847627  0.677955 -0.039102  0.424155  1.000000  0.914593
cute     1.000000  0.847627  0.677955 -0.039102  0.424155  1.000000  0.914593
bread    0.914593  0.560674  0.917311  0.368305  0.754128  0.914593  1.000000
eat      0.677955  0.184613  1.000000  0.708032  0.953260  0.677955  0.917311
cake     0.424155 -0.120974  0.953260  0.888312  1.000000  0.424155  0.754128
rice    -0.039102 -0.563331  0.708032  1.000000  0.888312 -0.039102  0.368305

In [251]:
temp.T[temp.T[1] > 0][1].to_dict()

{'kitty': 1.0000000000000002,
 'hamster': 0.8476267357426155,
 'cute': 0.8476267357426152,
 'bread': 0.560674315082687,
 'eat': 0.18461264781848385}

### Exam2

In [3]:
A = [
    [1, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 0, 1],
]

In [4]:
doc = ["문서1", "문서2", "문서3", "문서4", "문서5", "문서6"]
term = ["cosmonaut", "astronaut", "moon", "car", "truck"]

In [5]:
pd.DataFrame(A, columns=doc, index=term)

           문서1  문서2  문서3  문서4  문서5  문서6
cosmonaut    1    0    1    0    0    0
astronaut    0    1    0    0    0    0
moon         1    1    0    0    0    0
car          1    0    0    1    1    0
truck        0    0    0    1    0    1

In [6]:
U, sigma, VT = np.linalg.svd(A, full_matrices=False)
U.shape, sigma.shape, VT.shape

((5, 5), (5,), (5, 6))

In [7]:
_sigma = np.diag(sigma)
pd.DataFrame(_sigma)

          0         1        2    3         4
0  2.162501  0.000000  0.00000  0.0  0.000000
1  0.000000  1.594382  0.00000  0.0  0.000000
2  0.000000  0.000000  1.27529  0.0  0.000000
3  0.000000  0.000000  0.00000  1.0  0.000000
4  0.000000  0.000000  0.00000  0.0  0.393915

In [30]:
# _U = U[:, :2].dot(_sigma[:2])
# pd.DataFrame(U[:, :2].dot(_sigma[:2]), index=term)

_U = U.dot(_sigma)
pd.DataFrame(U.dot(_sigma), index=term)

                  0         1         2             3         4
cosmonaut  0.952252 -0.472215 -0.726275  5.773503e-01 -0.097062
astronaut  0.279712 -0.528459  0.748623  9.436896e-16 -0.286454
moon       1.028335 -0.814913  0.468911  4.518514e-16  0.242005
car        1.520282  0.558946 -0.197550 -5.773503e-01 -0.062943
truck      0.568030  1.031162  0.528725  5.773503e-01  0.034119

In [31]:
# _V = _sigma[:, :2].dot(VT[:2, :])
# pd.DataFrame(_sigma[:, :2].dot(VT[:2, :]), columns=doc)

_V = _sigma.dot(VT)
pd.DataFrame(_sigma.dot(VT), columns=doc)

            문서1           문서2       문서3           문서4       문서5       문서6
0  1.618898e+00  6.048766e-01  0.440347  9.656932e-01  0.703020  0.262673
1 -4.567172e-01 -8.425659e-01 -0.296174  9.973192e-01  0.350572  0.646747
2 -3.567135e-01  9.547117e-01 -0.569498  2.596858e-01 -0.154906  0.414592
3 -4.162907e-16  1.066959e-15  0.577350  2.382035e-16 -0.577350  0.577350
4  2.081681e-01 -1.128386e-01 -0.246402 -7.317416e-02 -0.159788  0.086614

In [32]:
# Latent Sematic 차원에서의 Term의 cosine similarity
cos_sim_U = _U.dot(_U.T) / (np.linalg.norm(_U, axis=1).reshape(5,1) * np.linalg.norm(_U.T, axis=0))
pd.DataFrame(cos_sim_U, index=term, columns=term)

,cosmonaut,astronaut,moon,car,truck
cosmonaut,1.000000e+00,-8.003345e-17,5.000000e-01,4.082483e-01,-4.413419e-16
astronaut,-8.003345e-17,1.000000e+00,7.071068e-01,-7.507526e-17,-5.039740e-16
moon,5.000000e-01,7.071068e-01,1.000000e+00,4.082483e-01,-5.870100e-16
car,4.082483e-01,-7.507526e-17,4.082483e-01,1.000000e+00,4.082483e-01
truck,-4.413419e-16,-5.039740e-16,-5.870100e-16,4.082483e-01,1.000000e+00

In [33]:
# Latent Sematic 차원에서의 Document의 cosine similarity
cos_sim_V = _V.T.dot(_V) / (np.linalg.norm(_V.T, axis=1).reshape(6,1) * np.linalg.norm(_V, axis=0))
pd.DataFrame(cos_sim_V, columns=doc, index=doc)

,문서1,문서2,문서3,문서4,문서5,문서6
문서1,1.000000e+00,4.082483e-01,5.773503e-01,4.082483e-01,5.773503e-01,-2.963221e-16
문서2,4.082483e-01,1.000000e+00,-6.043585e-16,-3.191787e-17,1.958219e-16,-3.068408e-16
문서3,5.773503e-01,-6.043585e-16,1.000000e+00,-7.827190e-16,-2.512096e-16,-6.821001e-16
문서4,4.082483e-01,-3.191787e-17,-7.827190e-16,1.000000e+00,7.071068e-01,7.071068e-01
문서5,5.773503e-01,1.958219e-16,-2.512096e-16,7.071068e-01,1.000000e+00,1.483248e-16
문서6,-2.963221e-16,-3.068408e-16,-6.821001e-16,7.071068e-01,1.483248e-16,1.000000e+00

In [48]:
cluster = pd.DataFrame(cos_sim_U, columns=term)
cluster

      cosmonaut     astronaut          moon           car         truck
0  1.000000e+00 -8.003345e-17  5.000000e-01  4.082483e-01 -4.413419e-16
1 -8.003345e-17  1.000000e+00  7.071068e-01 -7.507526e-17 -5.039740e-16
2  5.000000e-01  7.071068e-01  1.000000e+00  4.082483e-01 -5.870100e-16
3  4.082483e-01 -7.507526e-17  4.082483e-01  1.000000e+00  4.082483e-01
4 -4.413419e-16 -5.039740e-16 -5.870100e-16  4.082483e-01  1.000000e+00

In [49]:
temp = cluster.sort_values(by=[1], axis=1, ascending=False)
temp.T

,0,1,2,3,4
astronaut,-8.003345e-17,1.000000e+00,7.071068e-01,-7.507526e-17,-5.039740e-16
moon,5.000000e-01,7.071068e-01,1.000000e+00,4.082483e-01,-5.870100e-16
car,4.082483e-01,-7.507526e-17,4.082483e-01,1.000000e+00,4.082483e-01
cosmonaut,1.000000e+00,-8.003345e-17,5.000000e-01,4.082483e-01,-4.413419e-16
truck,-4.413419e-16,-5.039740e-16,-5.870100e-16,4.082483e-01,1.000000e+00

In [50]:
temp.T[temp.T[1] > 0][1].to_dict()    # astronaut와 moon가 유사하게 분석되었음(우주비행사.... 달...)

{'astronaut': 0.9999999999999999, 'moon': 0.7071067811865471}

In [61]:
cluster = pd.DataFrame(cos_sim_V, columns=doc)
cluster

,문서1,문서2,문서3,문서4,문서5,문서6
0,1.000000e+00,4.082483e-01,5.773503e-01,4.082483e-01,5.773503e-01,-2.963221e-16
1,4.082483e-01,1.000000e+00,-6.043585e-16,-3.191787e-17,1.958219e-16,-3.068408e-16
2,5.773503e-01,-6.043585e-16,1.000000e+00,-7.827190e-16,-2.512096e-16,-6.821001e-16
3,4.082483e-01,-3.191787e-17,-7.827190e-16,1.000000e+00,7.071068e-01,7.071068e-01
4,5.773503e-01,1.958219e-16,-2.512096e-16,7.071068e-01,1.000000e+00,1.483248e-16
5,-2.963221e-16,-3.068408e-16,-6.821001e-16,7.071068e-01,1.483248e-16,1.000000e+00

In [64]:
temp = cluster.T.sort_values(by=[1], axis=0, ascending=False)
temp

,0,1,2,3,4,5
문서2,4.082483e-01,1.000000e+00,-6.043585e-16,-3.191787e-17,1.958219e-16,-3.068408e-16
문서1,1.000000e+00,4.082483e-01,5.773503e-01,4.082483e-01,5.773503e-01,-2.963221e-16
문서5,5.773503e-01,1.958219e-16,-2.512096e-16,7.071068e-01,1.000000e+00,1.483248e-16
문서4,4.082483e-01,-3.191787e-17,-7.827190e-16,1.000000e+00,7.071068e-01,7.071068e-01
문서6,-2.963221e-16,-3.068408e-16,-6.821001e-16,7.071068e-01,1.483248e-16,1.000000e+00
문서3,5.773503e-01,-6.043585e-16,1.000000e+00,-7.827190e-16,-2.512096e-16,-6.821001e-16

In [67]:
temp[temp[1] > 0][1].to_dict()    # 문서5가 문서1, 문서2와 유사하게 분석된 것은 좀 이상함 ???

{'문서2': 1.0000000000000002,
 '문서1': 0.40824829046386313,
 '문서5': 1.958218726598256e-16}

### 뉴스 데이터에 SVD 적용한 Clustering

- 전처리 과정에서 명사만 선택하는 방식으로 개선 필요 (강사님 코드 참고...)

![getwords](./images/getwords_function.jpg)

![indexing](./images/indexing_function.jpg)

In [1]:
import pickle
import os
import numpy as np
import pandas as pd

In [2]:
with open("naver_news/pickle/news_collection.pickle", "rb") as f:
    news_collection = pickle.load(f)

In [3]:
full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("global_lexicon"))
with open(full_path, "rb") as f:
    global_lexicon = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("global_posting"))
with open(full_path, "rb") as f:
    global_posting = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("global_document"))
with open(full_path, "rb") as f:
    global_document = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("dtm"))
with open(full_path, "rb") as f:
    dtm = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("tdm"))
with open(full_path, "rb") as f:
    tdm = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("twm"))
with open(full_path, "rb") as f:
    twm = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("dtw"))
with open(full_path, "rb") as f:
    dtw = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("global_lexicon_idf"))
with open(full_path, "rb") as f:
    global_lexicon_idf = pickle.load(f)

full_path = os.path.join("naver_news/pickle/", "{0}.pickle".format("global_document_weight"))
with open(full_path, "rb") as f:
    global_document_weight = pickle.load(f)

In [4]:
from math import sqrt

In [5]:
# Similarity = Euclidean Distance
def euclidean(x1, x2):
    return sqrt(np.sum((x1 - x2) ** 2))

In [6]:
def cosine(x1, x2):
    _sum = np.sum(x1 * x2)
    return _sum / (np.linalg.norm(_x1) * np.linalg.norm(_x2))

In [7]:
def expectation(data, clusters, k=3, cos=True):
    distance = list()
    metric = cosine if cos else euclidean
    rvalue = max if cos else min
    
    distance = list()

    for i in range(k):
        distance.append(metric(data, clusters[i]))
        
    return distance.index(rvalue(distance))

In [8]:
def maximization(data):
    return np.sum(data, axis=0) / len(data)

In [9]:
def sse(data, centroid):   # sum squared error
    _sum = 0.0
    
    for _ in data:
        _sum += euclidean(_, centroid)
        
    return _sum

In [10]:
# 각각의 문서를 길이가 동일한 다차원 벡터로 만들기 (크기는 전체 Vocabulary 크기)
N = len(global_document)   # 전체 document 수
V = len(twm)   # term의 전체 차원 수(vocabulary 수)
K = 6

doc = [_ for _ in global_document]
voc = [_ for _ in global_lexicon.keys()]

# docVector = list(list(0.0 for _ in range(V)) for _ in range(N))
docVector = np.zeros(N * V).reshape(N, V)

for t_idx, (term, file_weights) in enumerate(twm.items()):
    for f_idx, (filename, weight) in enumerate(file_weights.items()):
        docVector[f_idx][t_idx] = weight

In [11]:
docVector

array([[ 3.48155781,  4.09199847, 55.57748944, ...,  2.77887447,
         2.77887447,  2.77887447],
       [ 3.48155781,  7.16099731,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 3.48155781, 10.22999616,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [12]:
pd.DataFrame(docVector, columns=voc, index=doc).head()

,앵커,불법,병역,면제,한국,사회의,고질적인,문제,하나가,아닐까,...,킨슨,슨병,급장,교세,기신,존시,든타,러허,색지,허정
00-01-0010682284.txt,3.481558,4.091998,55.577489,31.888336,1.834913,1.824632,2.477844,3.098540,2.079904,1.933776,...,2.778874,2.778874,2.778874,2.778874,2.778874,2.778874,2.778874,2.778874,2.778874,2.778874
00-02-0000205407.txt,3.481558,7.160997,0.000000,5.627353,12.385661,1.824632,2.477844,2.065694,2.079904,1.933776,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
00-03-0010704904.txt,3.481558,10.229996,0.000000,1.875784,1.376185,1.824632,0.000000,2.065694,4.159809,3.867553,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
00-04-0010682275.txt,3.481558,7.160997,0.000000,15.006276,2.293641,1.824632,0.000000,1.549270,2.079904,1.933776,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
00-05-0003433864.txt,3.481558,3.068999,0.000000,9.378922,0.917456,1.824632,0.000000,2.582117,2.079904,1.933776,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
U, sigma, VT = np.linalg.svd(docVector, full_matrices=False)
U.shape, sigma.shape, VT.shape

((600, 600), (600,), (600, 98060))

In [14]:
k = 10

In [15]:
_sigma = np.diag(sigma)
pd.DataFrame(_sigma[:k, :k])

,0,1,2,3,4,5,6,7,8,9
0,2254.55525,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.00000,1502.610106,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.00000,0.000000,1119.562475,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.00000,0.000000,0.000000,883.913124,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.00000,0.000000,0.000000,0.000000,750.353906,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.00000,0.000000,0.000000,0.000000,0.000000,626.349795,0.000000,0.000000,0.000000,0.000000
6,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,540.269763,0.000000,0.000000,0.000000
7,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,510.102444,0.000000,0.000000
8,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,458.065307,0.000000
9,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,412.784913

In [16]:
_U = U[:, :k].dot(_sigma[:k])
pd.DataFrame(U[:, :k].dot(_sigma[:k]), index=doc)

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
00-01-0010682284.txt,-1888.344020,790.799724,-163.925565,-5.409790,1.850461,-1.561351,0.117027,-0.049832,0.156120,-0.369992,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-02-0000205407.txt,-831.587100,-577.223111,833.028078,-351.112589,-36.030117,30.989795,-2.453253,3.539016,-1.053005,0.020716,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-03-0010704904.txt,-536.546640,-518.424509,110.849349,611.859591,418.017838,96.923214,-7.046382,7.884777,-4.858615,2.518874,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-04-0010682275.txt,-386.787711,-436.905214,-75.419442,226.214794,-252.273783,-498.620195,107.012307,77.589311,13.964543,-2.821446,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-05-0003433864.txt,-298.912728,-375.288869,-169.073240,108.935761,-258.835645,57.986752,-139.536125,-418.404257,35.221310,2.751785,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-06-0000933443.txt,-262.182221,-351.877855,-211.780015,59.002726,-253.173739,170.857329,-284.505109,255.123467,156.177369,-94.773891,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-07-0002892667.txt,-215.601571,-298.649301,-204.369507,1.724822,-161.143028,144.791004,1.151281,88.019396,-186.997002,305.799524,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-08-0000269602.txt,-180.587274,-265.475972,-184.046086,-29.674449,-89.890099,83.818388,111.619179,50.574766,-193.080753,-97.083662,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-09-0000718244.txt,-158.366893,-231.986426,-183.226236,-67.654018,-33.861221,83.485119,121.779186,27.194977,-87.418497,-66.773688,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00-10-0002892709.txt,-137.833590,-212.661528,-177.535843,-76.393743,-8.010319,83.224250,129.162942,-36.041613,-42.528922,-92.203438,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-01-0000933452.txt,-126.291418,-197.608008,-168.149953,-71.235772,11.184332,64.319341,129.742101,9.915319,16.809517,-80.017071,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-02-0010682283.txt,-115.545891,-187.629986,-164.196093,-93.437559,22.335029,55.479966,110.598048,-19.615468,66.736991,-69.448726,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-03-0001335011.txt,-104.360566,-167.041523,-148.112680,-83.972786,41.089170,48.160313,92.759601,-1.513848,51.482341,-24.563809,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-04-0000179506.txt,-96.780524,-159.348063,-144.197489,-95.824703,65.719217,27.008547,80.753465,-11.135707,63.741961,-5.889312,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-05-0000205430.txt,-90.340428,-151.422977,-145.412235,-105.852417,69.944634,6.569462,67.904631,-7.973698,67.633332,28.920571,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-06-0003523418.txt,-81.542888,-137.804043,-138.043899,-108.590665,78.143561,4.886223,65.452745,-9.496347,93.751370,36.662805,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-07-0010682281.txt,-73.133055,-127.463363,-124.340296,-104.665610,84.979522,-15.777322,19.237129,-9.496861,67.779581,39.117267,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-08-0004110149.txt,-62.958767,-111.926348,-109.178075,-95.852433,73.373599,-13.861565,21.535662,-11.460145,50.284074,35.671205,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-09-0002447056.txt,-58.748588,-104.461220,-100.646177,-91.715029,74.025571,-25.441858,-1.723564,0.757697,48.574273,43.026924,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-10-0010700264.txt,-58.159013,-104.091992,-108.217450,-93.724361,85.532075,-38.294519,-19.807382,4.591354,52.660011,44.041194,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-01-0000205405.txt,-54.672056,-100.593101,-105.016840,-96.525903,87.365085,-43.117475,-31.247897,0.402847,45.329731,42.728613,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-02-0010682272.txt,-51.479022,-95.085802,-94.554505,-95.078690,80.694687,-39.531778,-17.633481,-0.434184,44.529237,47.839084,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-03-0000718222.txt,-49.488087,-92.488080,-98.843505,-94.658837,87.191725,-44.540694,-23.236986,-1.815758,45.271896,58.615332,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-04-0000933437.txt,-46.112801,-84.902673,-89.939844,-89.840648,80.057573,-42.631051,-33.900744,-3.252795,16.723097,40.442826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-05-0010704752.txt,-44.850371,-86.827220,-92.534425,-82.721797,79.597960,-52.046885,-37.470233,6.548492,31.790710,33.166864,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-06-0001335002.txt,-40.212145,-77.942615,-83.885258,-76.056267,74.489784,-42.899462,-43.778280,1.837785,29.246025,25.135079,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-07-0000933455.txt,-33.543098,-61.971856,-67.013478,-67.584059,62.539525,-34.917201,-37.804992,-2.737149,-3.979287,10.327698,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-08-0003433858.txt,-32.782664,-61.200449,-67.628080,-67.299445,63.946197,-35.211585,-39.952706,-0.361172,-0.929295,9.037191,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-09-0000269592.txt,-30.729803,-57.347692,-61.987003,-63.512946,59.485227,-36.053255,-40.566611,-3.636122,-5.460938,6.775787,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
02-10-0009122687.txt,-27.413245,-51.891894,-55.462077,-57.505717,54.662208,-33.092422,-40.097950,-4.363601,-15.734639,-0.782281,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
03-01-0002900571.txt,-0.000123,-0.000226,-0.000272,-0.000351,0.000350,-0.000575,-0.000735,0.000073,-0.000941,-0.000585,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-02-0002900293.txt,-0.000159,-0.000302,-0.000363,-0.000463,0.000469,-0.000752,-0.000972,0.000080,-0.001251,-0.000772,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-03-0010692639.txt,-0.000005,-0.000016,-0.000020,-0.000022,0.000027,-0.000032,-0.000047,-0.000006,-0.000065,-0.000037,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-04-0004127183.txt,-0.000007,-0.000021,-0.000027,-0.000029,0.000035,-0.000043,-0.000063,-0.000008,-0.000087,-0.000049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-05-0002803080.txt,-0.000012,-0.000036,-0.000045,-0.000049,0.000060,-0.000072,-0.000106,-0.000013,-0.000146,-0.000082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-06-0001281895.txt,-0.000003,-0.000008,-0.000010,-0.000011,0.000013,-0.000016,-0.000024,-0.000003,-0.000033,-0.000018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-07-0002521762.txt,-0.000007,-0.000020,-0.000025,-0.000027,0.000033,-0.000040,-0.000059,-0.000007,-0.000081,-0.000046,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-08-0003540214.txt,-0.000002,-0.000007,-0.000008,-0.000009,0.000011,-0.000013,-0.000020,-0.000002,-0.000027,-0.000015,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-09-0002450794.txt,-0.000005,-0.000015,-0.000018,-0.000020,0.000024,-0.000029,-0.000043,-0.000005,-0.000060,-0.000033,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-10-0002900507.txt,-0.000005,-0.000013,-0.000017,-0.000018,0.000022,-0.000027,-0.000039,-0.000005,-0.000054,-0.000030,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-01-0000169598.txt,-0.000002,-0.000005,-0.000007,-0.000007,0.000009,-0.000011,-0.000016,-0.000002,-0.000022,-0.000012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-02-0002935381.txt,-0.000007,-0.000021,-0.000027,-0.000029,0.000035,-0.000043,-0.000063,-0.000008,-0.000087,-0.000049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-03-0003946163.txt,-0.000010,-0.000028,-0.000035,-0.000038,0.000046,-0.000056,-0.000082,-0.000010,-0.000114,-0.000064,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-04-0000725463.txt,-0.000009,-0.000025,-0.000032,-0.000035,0.000042,-0.000051,-0.000074,-0.000009,-0.000103,-0.000058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-05-0002900605.txt,-0.000002,-0.000005,-0.000007,-0.000007,0.000009,-0.000011,-0.000016,-0.000002,-0.000022,-0.000012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-06-0010772850.txt,-0.000005,-0.000016,-0.000020,-0.000022,0.000027,-0.000032,-0.000047,-0.000006,-0.000065,-0.000037,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-07-0000207901.txt,-0.000005,-0.000016,-0.000020,-0.000022,0.000027,-0.000032,-0.000047,-0.000006,-0.000065,-0.000037,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-08-0000207902.txt,-0.000005,-0.000013,-0.000017,-0.000018,0.000022,-0.000027,-0.000039,-0.000005,-0.000054,-0.000030,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-09-0003945984.txt,-0.000010,-0.000029,-0.000037,-0.000040,0.000049,-0.000059,-0.000086,-0.000011,-0.000119,-0.000067,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
04-10-0002991964.txt,-0.000004,-0.000012,-0.000015,-0.000016,0.000020,-0.000024,-0.000035,-0.000004,-0.000049,-0.000027,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-01-0002450769.txt,-0.000004,-0.000012,-0.000015,-0.000016,0.000020,-0.000024,-0.000035,-0.000004,-0.000049,-0.000027,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-02-0003946068.txt,-0.000006,-0.000019,-0.000023,-0.000026,0.000031,-0.000037,-0.000055,-0.000007,-0.000076,-0.000043,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-03-0010772572.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-04-0010692807.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-05-0002803126.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-06-0000432069.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-07-0002521802.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-08-0002450642.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-09-0000489480.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05-10-0002900643.txt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
_U.shape

(600, 600)

In [18]:
_V = _sigma[:, :k].dot(VT[:k, :])
pd.DataFrame(_sigma[:, :k].dot(VT[:k, :]), columns=voc)

,앵커,불법,병역,면제,한국,사회의,고질적인,문제,하나가,아닐까,...,킨슨,슨병,급장,교세,기신,존시,든타,러허,색지,허정
0,-13.162514,-18.662985,-46.549944,-34.032658,-13.365286,-4.143736,-2.989311,-7.835686,-4.131777,-4.251295,...,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497,-2.327497
1,-20.837338,-28.316062,29.249546,5.245641,-20.970489,-3.395186,0.352194,-9.678601,-2.263804,-2.941948,...,1.462477,1.462477,1.462477,1.462477,1.462477,1.462477,1.462477,1.462477,1.462477,1.462477
2,-21.966556,-21.729971,-8.137618,-4.438766,-10.711693,-1.004029,1.480875,-10.478323,1.200701,0.397545,...,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881,-0.406881
3,-21.532515,-17.483573,-0.340149,4.180633,-20.482534,1.020858,-0.999427,-10.238349,2.829201,2.763286,...,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007,-0.017007
4,21.228668,21.215972,0.137061,-9.953312,11.957703,-2.055073,-0.112869,10.464053,0.805920,-0.318459,...,0.006853,0.006853,0.006853,0.006853,0.006853,0.006853,0.006853,0.006853,0.006853,0.006853
5,-12.456905,-9.172457,-0.138542,-8.368924,-4.593292,0.979702,0.116419,-6.913050,-0.721777,0.303457,...,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927,-0.006927
6,-17.253905,-10.351856,0.012039,-2.064915,-9.378170,0.443693,-0.010715,-12.942323,-0.188456,-1.189418,...,0.000602,0.000602,0.000602,0.000602,0.000602,0.000602,0.000602,0.000602,0.000602,0.000602
7,-1.457747,2.062545,-0.005429,-2.021350,1.083724,0.689004,0.016949,-1.161068,-1.311121,0.081834,...,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271,-0.000271
8,-13.053107,-4.658896,0.018942,1.518897,-19.740224,-2.605307,-0.004852,-12.811759,0.175140,0.032726,...,0.000947,0.000947,0.000947,0.000947,0.000947,0.000947,0.000947,0.000947,0.000947,0.000947
9,-7.499882,-2.679469,-0.049816,-0.400470,-16.922022,-0.640497,-0.002097,-6.540930,0.023273,1.010231,...,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491,-0.002491
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
572,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
573,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
574,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
575,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
576,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
577,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
579,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
581,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
582,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
583,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
584,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
585,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
586,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
587,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
588,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
589,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
590,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
591,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
592,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
593,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
594,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
595,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
596,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
597,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
598,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
599,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
_V.shape

(600, 98060)

In [20]:
# Latent Sematic 차원에서의 Document의 cosine similarity
cos_sim_U = _U.dot(_U.T) / (np.linalg.norm(_U, axis=1).reshape(-1,1) * np.linalg.norm(_U.T, axis=0))
pd.DataFrame(cos_sim_U, index=doc, columns=doc)

/Users/alex/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide

/Users/alex/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide

,00-01-0010682284.txt,00-02-0000205407.txt,00-03-0010704904.txt,00-04-0010682275.txt,00-05-0003433864.txt,00-06-0000933443.txt,00-07-0002892667.txt,00-08-0000269602.txt,00-09-0000718244.txt,00-10-0002892709.txt,...,05-01-0002450769.txt,05-02-0003946068.txt,05-03-0010772572.txt,05-04-0010692807.txt,05-05-0002803126.txt,05-06-0000432069.txt,05-07-0002521802.txt,05-08-0002450642.txt,05-09-0000489480.txt,05-10-0002900643.txt
00-01-0010682284.txt,1.000000,0.351038,0.267026,0.226288,0.195542,0.170194,0.165228,0.169321,0.181625,0.159937,...,0.005193,0.005193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-02-0000205407.txt,0.351038,1.000000,0.423657,0.367159,0.297553,0.246455,0.234988,0.264555,0.264494,0.236408,...,0.022101,0.022101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-03-0010704904.txt,0.267026,0.423657,1.000000,0.452840,0.382774,0.327821,0.310425,0.339067,0.330219,0.308726,...,0.037846,0.037846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-04-0010682275.txt,0.226288,0.367159,0.452840,1.000000,0.490460,0.417136,0.393682,0.474108,0.426365,0.359906,...,0.098646,0.098646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-05-0003433864.txt,0.195542,0.297553,0.382774,0.490460,1.000000,0.507168,0.496950,0.488481,0.488718,0.534634,...,0.086920,0.086920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-06-0000933443.txt,0.170194,0.246455,0.327821,0.417136,0.507168,1.000000,0.544848,0.527826,0.520290,0.439273,...,0.039974,0.039974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-07-0002892667.txt,0.165228,0.234988,0.310425,0.393682,0.496950,0.544848,1.000000,0.695110,0.667750,0.537704,...,0.024223,0.024223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-08-0000269602.txt,0.169321,0.264555,0.339067,0.474108,0.488481,0.527826,0.695110,1.000000,0.962207,0.896949,...,0.313731,0.313731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-09-0000718244.txt,0.181625,0.264494,0.330219,0.426365,0.488718,0.520290,0.667750,0.962207,1.000000,0.972873,...,0.207076,0.207076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00-10-0002892709.txt,0.159937,0.236408,0.308726,0.359906,0.534634,0.439273,0.537704,0.896949,0.972873,1.000000,...,0.176736,0.176736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-01-0000933452.txt,0.157288,0.227468,0.325320,0.385128,0.446536,0.483126,0.495331,0.837063,0.948431,0.975660,...,0.075719,0.075719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-02-0010682283.txt,0.142936,0.224354,0.276281,0.340050,0.473486,0.463125,0.419592,0.726668,0.879170,0.939387,...,0.025739,0.025739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-03-0001335011.txt,0.151066,0.226674,0.311478,0.331391,0.431194,0.453364,0.493427,0.716450,0.876647,0.919720,...,0.026065,0.026065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-04-0000179506.txt,0.138983,0.218365,0.295459,0.309460,0.398488,0.388484,0.448768,0.625462,0.807479,0.862384,...,0.043321,0.043321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-05-0000205430.txt,0.131040,0.199748,0.252707,0.312758,0.367821,0.355689,0.472564,0.554705,0.745432,0.791872,...,0.040819,0.040819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-06-0003523418.txt,0.119866,0.179059,0.222748,0.265652,0.323887,0.320921,0.406523,0.454549,0.666421,0.725697,...,-0.026307,-0.026307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-07-0010682281.txt,0.114200,0.188753,0.230767,0.274233,0.329763,0.330210,0.411492,0.423265,0.619825,0.668382,...,0.127652,0.127652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-08-0004110149.txt,0.109270,0.190584,0.215829,0.270005,0.329824,0.306031,0.426333,0.444475,0.637020,0.684259,...,0.145715,0.145715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-09-0002447056.txt,0.106514,0.191262,0.211806,0.279949,0.294737,0.329913,0.422816,0.384939,0.568817,0.600441,...,0.192288,0.192288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01-10-0010700264.txt,0.101492,0.156790,0.204573,0.272793,0.266139,0.328586,0.379534,0.328047,0.505815,0.534835,...,0.243948,0.243948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-01-0000205405.txt,0.092741,0.153195,0.186222,0.256573,0.262984,0.311534,0.360972,0.305379,0.474980,0.503678,...,0.299660,0.299660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-02-0010682272.txt,0.090472,0.172424,0.174783,0.256463,0.251199,0.281552,0.373725,0.303844,0.481023,0.510608,...,0.252321,0.252321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-03-0000718222.txt,0.085146,0.141493,0.167312,0.240317,0.234004,0.254540,0.368329,0.261517,0.437068,0.464559,...,0.252263,0.252263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-04-0000933437.txt,0.089762,0.152880,0.163897,0.236502,0.246646,0.260080,0.376463,0.317432,0.465478,0.484058,...,0.398761,0.398761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-05-0010704752.txt,0.080052,0.132903,0.178238,0.279949,0.230329,0.303384,0.332860,0.288536,0.440547,0.459432,...,0.375004,0.375004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-06-0001335002.txt,0.078849,0.130365,0.177616,0.246006,0.245598,0.316763,0.311261,0.274168,0.424220,0.448697,...,0.403515,0.403515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-07-0000933455.txt,0.087439,0.144913,0.159613,0.220844,0.240391,0.266268,0.321698,0.355528,0.470754,0.486225,...,0.567284,0.567284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-08-0003433858.txt,0.084551,0.135309,0.157959,0.213797,0.226371,0.275353,0.305109,0.339183,0.456713,0.472654,...,0.562448,0.562448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-09-0000269592.txt,0.083147,0.140892,0.152669,0.218766,0.237560,0.260480,0.295223,0.337645,0.445155,0.460986,...,0.600006,0.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02-10-0009122687.txt,0.078587,0.139746,0.151724,0.208245,0.234419,0.246760,0.282533,0.367120,0.452883,0.464305,...,0.678605,0.678605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
03-01-0002900571.txt,0.031185,0.047648,0.022526,0.149395,0.036767,0.086890,0.012699,0.305286,0.193691,0.147133,...,0.991124,0.991124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-02-0002900293.txt,0.029200,0.045708,0.023722,0.145576,0.040658,0.083327,0.013596,0.306130,0.194846,0.149509,...,0.992435,0.992435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-03-0010692639.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-04-0004127183.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-05-0002803080.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-06-0001281895.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-07-0002521762.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-08-0003540214.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-09-0002450794.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03-10-0002900507.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-01-0000169598.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-02-0002935381.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-03-0003946163.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-04-0000725463.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-05-0002900605.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-06-0010772850.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-07-0000207901.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-08-0000207902.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-09-0003945984.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04-10-0002991964.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-01-0002450769.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-02-0003946068.txt,0.005193,0.022101,0.037846,0.098646,0.086920,0.039974,0.024223,0.313731,0.207076,0.176736,...,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-03-0010772572.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-04-0010692807.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-05-0002803126.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-06-0000432069.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-07-0002521802.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-08-0002450642.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-09-0000489480.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05-10-0002900643.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
cos_sim_U.shape

(600, 600)

In [ ]:
# Latent Sematic 차원에서의 Term의 cosine similarity
cos_sim_V = _V.T.dot(_V) / (np.linalg.norm(_V.T, axis=1).reshape(-1,1) * np.linalg.norm(_V, axis=0))
pd.DataFrame(cos_sim_V, columns=doc, index=doc)